CREATE DATABASE IF NOT EXISTS CoffeeDb;
use CoffeeDb;

DROP TABLE IF EXISTS Roaster, Cultivar, Roast, RoastCultivar, BrewerCategory, Brewer, Brew;

CREATE TABLE CoffeeDb.Roaster (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(20),
  country VARCHAR(3),
  PRIMARY KEY (id)
);

CREATE TABLE CoffeeDb.Cultivar (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  country VARCHAR(3) NOT NULL,
  maslMin SMALLINT UNSIGNED NOT NULL,
  maslMax SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE CoffeeDb.Roast (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  roaster SMALLINT UNSIGNED NOT NULL,
  roastLevel SMALLINT UNSIGNED NOT NULL,
  sweetness SMALLINT UNSIGNED NOT NULL,
  acidity SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (roaster) REFERENCES CoffeeDb.Roaster(id)
);

CREATE TABLE CoffeeDb.RoastCultivar (
  roast SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  cultivar SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (roast, cultivar),
  FOREIGN KEY (roast) REFERENCES CoffeeDb.Roast(id),
  FOREIGN KEY (cultivar) REFERENCES CoffeeDb.Cultivar(id)
);

CREATE TABLE CoffeeDb.BrewerCategory (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE CoffeeDb.Brewer (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  minGrind SMALLINT UNSIGNED NOT NULL,
  maxGrind SMALLINT UNSIGNED NOT NULL,
  speed SMALLINT UNSIGNED NOT NULL,
  strengthMin SMALLINT UNSIGNED NOT NULL,
  strengthMax SMALLINT UNSIGNED NOT NULL,
  clarity SMALLINT UNSIGNED NOT NULL,
  category SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (category) REFERENCES CoffeeDb.BrewerCategory(id)
);

CREATE TABLE CoffeeDb.Brew (
  id SMALLINT UNSIGNED NOT NULL,
  coffeeWeight FLOAT UNSIGNED NOT NULL,
  roast SMALLINT UNSIGNED,
  grindSize FLOAT UNSIGNED,
  temperature FLOAT,
  clarity SMALLINT UNSIGNED NOT NULL,
  sweetness SMALLINT UNSIGNED NOT NULL,
  bitterness SMALLINT UNSIGNED NOT NULL,
  sourness SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (roast) REFERENCES CoffeeDb.Roast(id)
);
