CREATE DATABASE IF NOT EXISTS CoffeeDb;
DROP TABLE IF EXISTS Roaster;
CREATE TABLE Roaster (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(20),
  country VARCHAR(3),
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS Cultivar;
CREATE TABLE Cultivar (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(20),
  country VARCHAR(3),
  maslMin SMALLINT UNSIGNED NOT NULL,
  maslMax SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
);

DROP TABLE IF EXISTS Roast;
CREATE TABLE Roast (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  roastLevel SMALLINT UNSIGNED NOT NULL,
  sweetness SMALLINT UNSIGNED NOT NULL,
  acidity SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS RoastCultivar;
CREATE TABLE RoastCultivar (
  roast SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  cultivar SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (roast, cultivar),
  FOREIGN KEY roast REFERENCES Roast(id),
  FOREIGN KEY cultivavr REFERENCES Cultivar(id)
);

DROP TABLE IF EXISTS RoastRoaster;
CREATE TABLE RoastRoaster (
  roast SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  roaster SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (roast, roaster),
  FOREIGN KEY roast REFERENCES Roast(id),
  FOREIGN KEY roaster REFERENCES Roaster(id)
);

DROP TABLE IF EXISTS BrewerCategory;
CREATE TABLE BrewerCategory (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS Brewer;
CREATE TABLE Brewer (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  minGrind SMALLINT UNSIGNED NOT NULL,
  maxGrind SMALLINT UNSIGNED NOT NULL,
  speed SMALLINT UNSIGNED NOT NULL,
  strengthMin SMALLINT UNSIGNED NOT NULL,
  strengthMax SMALLINT UNSIGNED NOT NULL,
  clarity SMALLINT UNSIGNED NOT NULL
  category SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY category REFERENCES BrewerCategory(id)
);

DROP TABLE IF EXISTS User;
CREATE TABLE User (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  email VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
);
